# history
history:
    path: /api/equations
    defaults:
        resource: Application\Controller\Equations
        action: collection
    methods: [GET]


calc:
    path: /api/equations
    defaults:
        resource: Application\Controller\Equations
        action: resource
    methods: [POST]


equation:
    path: /api/equations/{id}
    requirements:
        id: "[0-9]+"
    defaults:
        resource: Application\Controller\Equations
        action: resource
    methods: [GET]
